name: b2b_v2

services:
  postgres18:
    container_name: pg18

    build:
      context: ./postgres

    secrets:
      - pg_password

    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password

    ports:
      - ${PG_PORT_LOCAL}:${PG_PORT_DKR}

    volumes:
      - /var/lib/pg/data:/var/lib/postgresql/18/docker
      - ./postgres/sql:/docker-entrypoint-initdb.d

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${PG_USER} -d ${PG_DATABASE}'"]
      interval: 10s
      timeout: 5s
      retries: 5

  node24:
    container_name: node24

    build:
      context: ./node

    secrets:
      - pg_password
      - dnb_dpl_key
      - dnb_dpl_secret

    environment:
      - PG_HOST=${PG_HOST}
      - PG_DATABASE=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PORT=${PG_PORT_LOCAL}
      - NODE_ENV=${NODE_ENV}
      - API_SERVER_PORT=${API_SERVER_PORT}

    depends_on:
      postgres18:
        condition: service_healthy

    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}

    restart: unless-stopped

secrets:
   pg_password:
      file: ${HOME}/.secrets/pg_password
   dnb_dpl_key:
      file: ${HOME}/.secrets/dnb_dpl_key
   dnb_dpl_secret:
      file: ${HOME}/.secrets/dnb_dpl_secret
