name: b2b_v2

services:
  postgres18:
    container_name: pg18

    build:
      context: ./postgres

    secrets:
      - pg_password

    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER} 
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password

    ports:
      - ${PG_PORT_LOCAL}:${PG_PORT_DKR}

    restart: unless-stopped

secrets:
   pg_password:
      file: ${HOME}/.secrets/db_pwd
