name: b2b_v2

services:
  postgres18:
    container_name: pg18

    build:
      context: ./postgres

    secrets:
      - pg_password

    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER} 
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password

    ports:
      - ${PG_PORT_LOCAL}:${PG_PORT_DKR}

    volumes:
      - /var/lib/pg/data:/var/lib/postgresql/18/docker
      - ./postgres/sql:/docker-entrypoint-initdb.d

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${PG_USER} -d ${PG_DATABASE}'"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
   pg_password:
      file: ${HOME}/.secrets/db_pwd
