FROM node:24.18-trixie-slim

# App directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# Install the dependencies (excl.dev)
RUN npm ci --omit=dev

# Deliver source code
COPY ./src ./src

USER node

# Start application
CMD [ "npm", "start" ]
